export default {
  listEmpty: 'No data found',
  dataNew: 'Add',
  dataEdit: 'Edit',
  dataDelete: 'Delete',
  dataFilter: 'Filter',
  dataSearch: 'Search',
  dataOrderBy: 'Order by',
  dataClose: 'Close',
  dataMoreOptions: 'More options',
  dataOrderOptionsAZ: 'A-Z',
  dataOrderOptionsZA: 'Z-A',
  dataFilterBy: 'Filter by',
  dataFilterOptionsAll: 'All',
  buttonApply: 'Apply',
  buttonConfirm: 'Confirm',
  buttonSave: 'Save',
  buttonPublish: 'Publish',
  buttonDelete: 'Delete',
  buttonFinish: 'Finish',
  buttonClose: 'Close',
  buttonOpen: 'Open',
  buttonLogIn: 'Log in',
  formRequiredFields: 'Please, fill all the required fields.',
  formRequiredField: 'Required',
  languagePT: 'Portuguese',
  languageEN: 'English',
  changeToEnglish: 'Change to english',
  changeToPortuguese: 'Change to portuguese',
  profile: 'My profile',
  menu: 'Menu',
  menuHome: 'Home',
  menuSurveys: 'Surveys',
  menuQuestions: 'Questions',
  menuResults: 'Results',
  paginationBack: 'Previous',
  paginationNext: 'Next',
};
