export default {
  listEmpty: 'Registros não encontrados',
  dataNew: 'Adicionar',
  dataEdit: 'Editar',
  dataDelete: 'Excluir',
  dataFilter: 'Filtrar',
  dataSearch: 'Pesquisar',
  dataOrderBy: 'Ordernar por',
  dataClose: 'Fechar',
  dataMoreOptions: 'Mais opções',
  dataOrderOptionsAZ: 'A-Z',
  dataOrderOptionsZA: 'Z-A',
  dataFilterBy: 'Filtrar por',
  dataFilterOptionsAll: 'Todos',
  buttonApply: 'Aplicar',
  buttonConfirm: 'Confirmar',
  buttonSave: 'Salvar',
  buttonPublish: 'Publicar',
  buttonDelete: 'Excluir',
  buttonFinish: 'Finalizar',
  buttonLogIn: 'Entrar',
  buttonClose: 'Fechar',
  buttonOpen: 'Abrir',
  formRequiredFields: 'Por favor, preencha todos os campos obrigatórios.',
  formRequiredField: 'Campo obrigatório',
  languagePT: 'Português',
  languageEN: 'Inglês',
  changeToEnglish: 'Mudar para inglês',
  changeToPortuguese: 'Mudar para português',
  profile: 'Meu perfil',
  Menu: 'Menu',
  menuHome: 'Inicial',
  menuSurveys: 'Pesquisas',
  menuQuestions: 'Perguntas',
  menuResults: 'Resultados',
  paginationBack: 'Voltar',
  paginationNext: 'Avançar',
};
