export default {
  questionTitle: 'Question',
  questionList: 'Questions',
  questionListTypeSingleChoice: 'Single choice',
  questionListTypeMultipleChoice: 'Multiple choices',
  questionListTypeFreeText: 'Free text',
  questionListNoAnswer: 'Answer not registred',
  questionFilterBySurvey: 'Filter by survey',
  questionSearchBySurvey: 'Search by survey title...',
  questionsSelectSurveyToContinue: 'Select a survey to continue',
  questionFormNewTitle: 'New question',
  questionFormEditTitle: 'Edit question',
  questionFormDetailTitle: 'Question details',
  questionFormDescription: 'Description',
  questionFormAnswerTitle: 'Answer',
  questionFormAnswerType: 'Type',
  questionFormAnswerTypeFreeText: 'Free text',
  questionFormAnswerTypeFreeTextMinChar: 'Min. char',
  questionFormAnswerTypeFreeTextMaxChar: 'Max. char',
  questionFormAnswerTypeSingleChoice: 'Single choice',
  questionFormAnswerTemplate: 'Answer template',
  questionFormAnswerTemplateI: 'Template I',
  questionFormAnswerTemplateII: 'Template II',
  questionFormAnswerTypeMultipleChoice: 'Multiple choices',
  questionFormAnswerOptions: 'Options',
};
