export default {
  questionTitle: 'Pergunta',
  questionList: 'Perguntas',
  questionListTypeSingleChoice: 'Escolha única',
  questionListTypeMultipleChoice: 'Múltipla escolha',
  questionListTypeFreeText: 'Texto livre',
  questionListNoAnswer: 'Pergunta sem resposta',
  questionFilterBySurvey: 'Filtre por Pesquisa',
  questionSearchBySurvey: 'Procure pelo título da Pesquisa...',
  questionsSelectSurveyToContinue: 'Selecione uma Pesquisa para continuar',
  questionFormNewTitle: 'Nova pergunta',
  questionFormEditTitle: 'Editar pergunta',
  questionFormDetailTitle: 'Detalhes da pergunta',
  questionFormDescription: 'Descrição',
  questionFormAnswerTitle: 'Resposta',
  questionFormAnswerType: 'Tipo',
  questionFormAnswerTypeFreeText: 'Texto livre',
  questionFormAnswerTypeFreeTextMinChar: 'Qtd. Mínima',
  questionFormAnswerTypeFreeTextMaxChar: 'Qtd. Máxima',
  questionFormAnswerTypeSingleChoice: 'Escolha única',
  questionFormAnswerTemplate: 'Template da respostas',
  questionFormAnswerTemplateI: 'Template I',
  questionFormAnswerTemplateII: 'Template II',
  questionFormAnswerTypeMultipleChoice: 'Escolha múltipla',
  questionFormAnswerOptions: 'Opções',
};
