export default {
  surveyTitle: 'Survey',
  surveysList: 'Surveys',
  surveyStatusOffline: 'Offline',
  surveyStatusOnline: 'Online',
  surveyStatusPublishing: 'Publishing',
  surveyStatusFinished: 'Finished',
  surveyQuestions: 'Questions',
  surveyResults: 'Results',
  surveyDisplayOptions: 'Display options',
  surveyFormNewTitle: 'New survey',
  surveyFormEditTitle: 'Edit survey',
  surveyFormDetailTitle: 'Survey details',
  surveyFormTitle: 'Title',
  surveyFormDescription: 'Description',
  surveyFormPublicTitle: 'Public title',
  surveyFormPublicDescription: 'Public description',
  surveyFormConclusionMessage: 'Conclusion message',
  surveyPublishConfig: 'Publishing configuration',
  surveyPublishConfigStart: 'Start date',
  surveyPublishConfigFinish: 'Finish date',
  surveyPublishDetails: 'Publish details',
  surveyEditPublishing: 'Click to edit',
  surveyTotalQuestions: 'Total questions',
};
