export default {
  surveyTitle: 'Pesquisa',
  surveysList: 'Pesquisas',
  surveyStatusOffline: 'Offline',
  surveyStatusOnline: 'Online',
  surveyStatusPublishing: 'Publicando',
  surveyStatusFinished: 'Finalizado',
  surveyQuestions: 'Perguntas',
  surveyResults: 'Resultados',
  surveyDisplayOptions: 'Opções de visualização',
  surveyFormNewTitle: 'Nova Pesquisa',
  surveyFormEditTitle: 'Editar Pesquisa',
  surveyFormDetailTitle: 'Detalhes da Pesquisa',
  surveyFormTitle: 'Título',
  surveyFormDescription: 'Descrição',
  surveyFormPublicTitle: 'Título public',
  surveyFormPublicDescription: 'Descrição pública',
  surveyFormConclusionMessage: 'Mensagem de conclusão',
  surveyPublishConfig: 'Configurações de publicação',
  surveyPublishConfigStart: 'Data de ínicio',
  surveyPublishConfigFinish: 'Data de finalização',
  surveyPublishDetails: 'Detalhes da publicação',
  surveyEditPublishing: 'Clique para editar',
  surveyTotalQuestions: 'Total de perguntas',
};
